import { TopNav } from "@/components/nav/TopNav";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import { ThemeProvider } from "./context/theme";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Next Js Blog App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-bs-theme="dark">
      <ThemeProvider>
        <body>
          <TopNav />
          <Toaster />
          {children}
        </body>
      </ThemeProvider>
    </html>
  );
}
